name: Daily Advice in README

on:
  schedule:
    - cron: '30 11 * * *'  # 11:30 UTC = 4:00 PM Kabul time
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Essential write permission

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get complete history
          ref: master  # Explicitly checkout master branch

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Update README
        run: |
          # Ensure advices.txt exists
          if [ ! -f advices.txt ]; then
            echo "Stay positive!" > advices.txt
            echo "Keep learning every day." >> advices.txt
            echo "Be kind to others." >> advices.txt
            echo "Take breaks and rest." >> advices.txt
          fi

          # Get today's advice
          advice_count=$(wc -l < advices.txt)
          day_num=$(( ($(date -u +%s) / 86400) % advice_count + 1 ))
          advice=$(sed -n "${day_num}p" advices.txt)

          # Update README
          grep -v '^> 💡' README.md > README.tmp || true
          awk -v advice="> 💡 Today's Advice: $advice" '
            BEGIN {added=0}
            {print}
            /Najibullah Jafari/ && !added {print advice; added=1}
          ' README.tmp > README.md
          rm README.tmp

      - name: Commit and Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Configure Git
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Stage, commit and push
          git add README.md
          git commit -m "Update README with today's advice [skip ci]" || exit 0
          
          # Force push to handle any synchronization issues
          git push origin HEAD:master --force-with-lease
