name: Daily Advice in README

on:
  schedule:
    - cron: '30 11 * * *'  # 11:30 UTC = 4:00 PM Kabul time (UTC+4:30)
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Explicit write permissions

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get full history
          token: ${{ secrets.GITHUB_TOKEN }}  # Auth token

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Update README with daily advice
        run: |
          # Create/read advices.txt
          if [ ! -f advices.txt ]; then
            echo "Stay positive!" > advices.txt
            echo "Keep learning every day." >> advices.txt
            echo "Be kind to others." >> advices.txt
            echo "Take breaks and rest." >> advices.txt
          fi

          # Get today's advice
          advice_count=$(wc -l < advices.txt)
          day_num=$(( ($(date -u +%s) / 86400) % advice_count + 1 ))
          advice=$(sed -n "${day_num}p" advices.txt)

          # Update README
          grep -v '^> 💡' README.md > README.tmp || true
          awk -v advice="> 💡 Today's Advice: $advice" '
            BEGIN {added=0}
            {print}
            /Najibullah Jafari/ && !added {print advice; added=1}
          ' README.tmp > README.md
          rm README.tmp

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Configure git
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # Get latest changes
          git pull --ff-only origin master
          
          # Commit and push
          git add README.md
          git commit -m "Update README with today's advice [skip ci]" || exit 0
          git push origin HEAD:master
